### ISSUE TITLE
[request] Merge/update to latest upstream

### ISSUE THREAD

**Issue by stevenhoneyman** [rofl0r/hexedit0r#1]
Hi,

I like the changes you've made to hexedit - there is a newer version upstream now: http://www.cygwin.com/ml/cygwin-announce/2013-06/msg00027.html

Would you be able to apply your changes to the latest version and update?

Thanks,
Steven.

**Comment by rofl0r** [comment]
the latest work in this repo was done in oct 2013 and i already merged the only notable bugfix between 1.2.12 and .13, https://github.com/rofl0r/hexedit0r/commit/c11b6ce4ede831b73cc0395811e2d19b24df500e .
the other notable bugfix (the 2^31) one was already fixed in my version

so there's nothing missing compared to 1.2.13.
the only thing that may be interesting to merge is this post-1.2.13 commit:
https://github.com/pixel/hexedit/commit/af5e7225712b9de3d5d7e72f68f15217b5b38ee9
and its parent.

**Comment by stevenhoneyman** [comment]
There you go, saves you a job :smile: 

Just curious, why haven't the errors you've fixed been adopted upstream? I can understand them not wanting mods like color enabled by default etc, but the variable types etc - that's bugfixes/improvements, right?

**Comment by rofl0r** [comment]
in my eyes yes, but maybe not in pixel's... if you look at the comments in my first dozen commits you can see that pixel took a look at my fork a while ago; but since one of the commits had a bug maybe pixel had the impression that i don't do a good job.
